### ISSUE TITLE
Install location question

### ISSUE THREAD

**Issue by Phr3d13** [rpi-ws281x/rpi-ws281x-python#33]
Does this install method/repo install to the same location as the old repo (https://github.com/jgarff/rpi_ws281x/tree/master/python)? I didn't read the readme until after I followed an old guide for the old repo's method of building/installing (https://stackoverflow.com/questions/53045343/adafruit-raspberry-pi-neopixel-library-throws-error-importerror-no-module-name).

**Comment by Gadgetoid** [comment]
The use of the `neopixel` library name has been deprecated since version 4.0.0 (see #8) and this library installs as `rpi_ws281x`.

Similarly the Python bindings in jgarff's library are considered deprecated in favour of this library ( at least by me ), and they install as- IIRC- `adafruit_neopixel`.
